batch:
  voice-log-input: /tmp
  voice-log-output: /tmp
  voice-log-tmp: /tmp

sphinx:
  ffmpeg-path: /usr/local/bin/ffmpeg

elasticsearch:
  elastic-version: 5.5
  domain-arn: arn:aws:es:ap-southeast-1:744922890941:domain/cs-hackthon-marshmello